import { ReactNode } from 'react';

import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: 'Homepage',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className={`bg-red-500 h-10`}>
                    <Link href={`/products`}>
                        Product
                    </Link>
                </div>
                {children}
            </body>
        </html>
    );
};
